In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model 

In [2]:
df = pd.read_csv('C:/Users/ARIF RAJA MONDAL/Desktop/Machine Learning/Dummy Variable/dummy.csv')
df

city  area   price
0  kolkata  6789  765456
1    delhi  5677  567890
2   mumbai  3456  567899
3   mumbai  1234  123458
4    delhi  4354  535757
5  kolkata  5464  654356

In [5]:
dummies = pd.get_dummies(df.city)
dummies

delhi  kolkata  mumbai
0      0        1       0
1      1        0       0
2      0        0       1
3      0        0       1
4      1        0       0
5      0        1       0

In [9]:
merged = pd.concat([df,dummies],axis='columns')

In [12]:
final = merged.drop(['city'], axis = 'columns')
final

area   price  delhi  kolkata  mumbai
0  6789  765456      0        1       0
1  5677  567890      1        0       0
2  3456  567899      0        0       1
3  1234  123458      0        0       1
4  4354  535757      1        0       0
5  5464  654356      0        1       0

In [33]:
x = final.drop(['price'] , axis = 'columns')
x

area  delhi  kolkata  mumbai
0  6789      0        1       0
1  5677      1        0       0
2  3456      0        0       1
3  1234      0        0       1
4  4354      1        0       0
5  5464      0        1       0

In [34]:
y = final.price
y

0    765456
1    567890
2    567899
3    123458
4    535757
5    654356
Name: price, dtype: int64

In [35]:
from sklearn import linear_model

In [36]:
reg = linear_model.LinearRegression()

In [37]:
reg.fit(x,y)

LinearRegression()

In [38]:
test_d = pd.read_csv('C:/Users/ARIF RAJA MONDAL/Desktop/Machine Learning/Dummy Variable/dummy1.csv')
test_d

area  delhi  kolkata  mumbai 
0  3456      1        0        0
1  6547      0        0        1
2  6567      1        0        0
3  1234      0        1        0
4  4354      0        1        0
5  3456      0        0        1

In [41]:
test_res = reg.predict(test_d)
test_res

C:\Users\ARIF RAJA MONDAL\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- mumbai 
Feature names seen at fit time, yet now missing:
- mumbai

  warnings.warn(message, FutureWarning)


array([334377.48586662, 931576.64131995, 768154.04884767,  27729.26120707,
       462760.72263455, 500588.74155318])

In [32]:
reg.score(x,y)

0.902141747017921

In [43]:
test_d['price'] = test_res

In [45]:
test_d.to_csv("C:/Users/ARIF RAJA MONDAL/Desktop/Machine Learning/Dummy Variable/prediction.csv")

In [46]:
from sklearn.preprocessing import LabelEncoder

In [47]:
le = LabelEncoder();

In [49]:
label = df
label.city = le.fit_transform(label.city)

In [141]:
x = label.drop(['price'], axis = 'columns')
x

city  area
0     1  6789
1     0  5677
2     2  3456
3     2  1234
4     0  4354
5     1  5464

In [142]:
y = label.price

In [143]:
reg.fit(x,y)

LinearRegression()

In [101]:
reg.predict([[1,6576]])

C:\Users\ARIF RAJA MONDAL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([781414.76976104])

In [144]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [145]:
ohe = ColumnTransformer([('encoder', OneHotEncoder(), [0])],     remainder='passthrough')


In [146]:
np.shape(df)

(6, 3)

In [147]:
x = df[['city','area']].values
x

array([[   1, 6789],
       [   0, 5677],
       [   2, 3456],
       [   2, 1234],
       [   0, 4354],
       [   1, 5464]], dtype=int64)

In [148]:

x = ohe.fit_transform(x)
x = np.asarray(x)
np.shape(x)

(6, 4)

In [149]:
x = x[:,1:] # remove price column
np.shape(x)

(6, 3)

In [150]:
reg.fit(x,y)

LinearRegression()

In [151]:
reg.predict([[1,0,2343]])

array([182360.63643878])